test_task:
  container:
    matrix:
      image: registry.fedoraproject.org/fedora:rawhide
      image: registry.fedoraproject.org/fedora:latest
      image: centos:centos7
      image: centos:centos6
  test_script: tests/build.sh
