language: generic

sudo: required

services:
- docker

install: true

stages:
- build-and-test

matrix:
  include:
    - stage: build-and-test
      env: fedora=rawhide
    - stage: build-and-test
      env: fedora=28
    - stage: build-and-test
      env: centos=centos7
    - stage: build-and-test
      env: centos=centos6

before_script:
- if test -n "$fedora" ; then sed -i "s#^FROM.*#FROM registry.fedoraproject.org/fedora:$fedora#" tests/Dockerfile ; fi
- if test -n "$centos" ; then sed -i "s#^FROM.*#FROM centos:$centos#" tests/Dockerfile ; fi

script:
- docker build -t mod_authnz_pam -f tests/Dockerfile .
- docker run --name mod_authnz_pam --rm -d mod_authnz_pam
- docker exec mod_authnz_pam tests/run.sh
