FROM centos:centos7
RUN yum install -y rpm-build yum-utils
WORKDIR /src
COPY mod_authnz_pam.spec .
RUN yum-builddep -y mod_authnz_pam.spec
COPY * source/
RUN rpm -q --qf '%{name}-%{version}\n' --specfile mod_authnz_pam.spec | head -1 > name_version
RUN mv -v source $( cat name_version )
RUN mkdir -p ~/rpmbuild/SOURCES
RUN tar cvzf ~/rpmbuild/SOURCES/$( cat name_version ).tar.gz $( cat name_version )
RUN rpmbuild -bb --define "dist $( rpm --eval '%{dist}' ).localbuild" mod_authnz_pam.spec
RUN yum install -y ~/rpmbuild/RPMS/*/$( cat name_version )-*.localbuild.*.rpm
