name: Build and test mod_authnz_pam

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '38 4 3,17 * *'

jobs:
  build:
    name: Run tests in container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'registry.fedoraproject.org/fedora:rawhide'
          - 'registry.fedoraproject.org/fedora:latest'
          - 'quay.io/centos/centos:stream9'
          - 'quay.io/centos/centos:stream8'
          - 'registry.centos.org/centos:7'
    steps:
      - uses: actions/checkout@v3
      - name: Set the right OS in the Dockerfile
        run: sed -i "s#^FROM.*#FROM ${{ matrix.os }}#" tests/Dockerfile
      - name: Build image
        run: docker build -t mod_authnz_pam -f tests/Dockerfile .
      - name: Run container
        run: docker run --name mod_authnz_pam --rm -d mod_authnz_pam
      - name: Run tests in the container
        run: docker exec mod_authnz_pam tests/run.sh
